name: book_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  camera: ^0.11.0+2
  cloud_firestore: ^5.6.6
  collection: ^1.18.0
  connectivity_plus: ^6.1.3
  dartz: ^0.10.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.5
  flutter_bloc: ^9.1.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  formz: ^0.8.0
  get_it: ^8.0.3
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  stream_transform: ^2.1.1
  books_finder: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

flutter_native_splash:
  color: "#e06346"
  image: "assets/images/splash.png"
  android: true
  ios: true
  android_12:
    color: "#ffffff"
  
flutter_icons:
  image_path: "assets/images/app_icon.png"
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  adaptative_icon_background: "#ffffff"
  adaptative_icon_foreground: "assets/images/app_android_icon.png"
